---
title: "Analysis of Wessel direct replication 1"
output:
  pdf_document: default
  html_notebook: default
---

```{r message=FALSE, warning=FALSE}

use_checkpoint = TRUE

if (use_checkpoint) {
  library(checkpoint)
  checkpointDir <- '/checkpoint'
  checkpoint("2020-06-26", checkpointLocation = checkpointDir)
}

library(tidyverse)
library(lme4)
library(lmerTest)
```

Load data

```{r}
rep1Df = read_csv('../processed_data/wessel_replication_1.csv', )
rep1Df['X1'] = NULL
rep1Df = rep1Df %>% 
  mutate(studyNum = 1,
         stimValueFactor = as.factor(auctionStimValue))
rep2Df = read_csv('../processed_data/wessel_replication_2.csv')
rep2Df['X1'] = NULL
rep2Df = rep2Df %>% 
  mutate(studyNum = 2,
         auctionStimValue = recode(auctionStimValue,
                                   `5`=1, 
                                   `6`=2,
                                   `7`=3,
                                   `8`=4),
         stimValueFactor = as.factor(auctionStimValue),
         auctionCondition = recode(auctionCondition,
                                   `0`='go',
                                   `1`='stop'))

repDf = rbind(rep1Df, rep2Df)

```

## Visualization

Plot data for each study separately 

```{r}
ggplot(rep1Df, aes(stimValueFactor, chosenAuctionAmount, color=auctionCondition)) + 
  geom_boxplot()
```

Plot data for study 2.

```{r}
ggplot(rep2Df, aes(stimValueFactor, chosenAuctionAmount, color=auctionCondition)) + 
  geom_boxplot()
```

## Individual study models

Mixed effect model for study 1

```{r}
formula = 'chosenAuctionAmount ~ 
              auctionStimValue*auctionCondition + 
              (1 + auctionStimValue*auctionCondition|subcode)'

lmer_study1 = lmer(formula, data=rep1Df)
summary(lmer_study1)
```

```{r}
coefs = fixef(lmer_study1)
coefs[] = 0
coefs[4] = 10
newdata = simulate(lmer_study1, 
                   newparams= list('beta'=coefs),
                   newdata = rep1Df %>% dplyr::filter(subcode<40))
simdata=rep1Df
simdata$chosenAuctionAmount = newdata$sim_1
lmer_newdata = lmer(formula, data=simdata)
summary(lmer_newdata)
```


```{r}
# from https://stackoverflow.com/questions/25142901/standardized-coefficients-for-lmer-model
stdCoef.merMod <- function(object) {
  sdy <- sd(getME(object,"y"))
  sdx <- apply(getME(object,"X"), 2, sd)
  sc <- fixef(object)*sdx/sdy
  se.fixef <- coef(summary(object))[,"Std. Error"]
  se <- se.fixef*sdx/sdy
  return(data.frame(stdcoef=sc, stdse=se))
}

stdCoef.merMod(lmer_study1)

```




```{r}
formula = 'chosenAuctionAmount ~ 
              auctionStimValue*auctionCondition + 
              (1 + auctionStimValue*auctionCondition|subcode)'
lmer_study2 = lmer(formula, data=rep2Df)
summary(lmer_study2)
```

Combined model across studies

```{r}
formula = "chosenAuctionAmount ~ 
              auctionStimValue*auctionCondition + 
              (1 + auctionStimValue*auctionCondition|subcode) + 
              (1|studyNum)"
lmer_combined = lmer(formula, data=repDf)
summary(lmer_combined)

repDf['resid'] = summary(lmer_combined)$resid
```

## Diagnostics

Plot residuals against explanatory variables.

```{r}
library(psych)
pairs.panels(repDf %>% select(-chosenAuctionAmount, -subcode))
```

